name: rx_connectivity_checker_example
description: Example app for rx_connectivity_checker.
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.41.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  rx_connectivity_checker:
    path: ../
  universal_platform: ^1.1.0

  flutter_animate: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
