name: Test Flutter Windows Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter precache --windows

      # Go into example app
      - working-directory: example
        run: flutter pub get

      - working-directory: example
        run: flutter clean

      - working-directory: example
        run: flutter pub get

      - working-directory: example
        run: flutter build windows --release
